config/urls.py
from django.contrib import admin
from django.urls import path, include
from pybo import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('pybo/', include('pybo.urls')),
]

pybo/urls.py
from django.urls import path

from . import views

app_name = 'pybo'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:question_id>/', views.detail,name='detail'),
    path('answer/create/<int:question_id>/', views.answer_create, name='answer_create'),
]

pybo/models.py
from django.db import models

class Question(models.Model):
     subject = models.CharField(max_length=2000)
     content = models.TextField()
     create_date = models.DateTimeField()

     def __str__(self):
          return self.subject

class Answer(models.Model):
     question = models.ForeignKey(Question, on_delete=models.CASCADE)
     content = models.TextField()
     create_date = models.DateTimeField()

pybo/views.py
from django.shortcuts import render, get_object_or_404,redirect
from .models import Question
from django.utils import timezone

def index(request):

    """
    pybo 몰록 출력
    """
    question_list = Question.objects.order_by('-create_date')
    context = {'question_list' : question_list}
    return render(request, 'pybo/question_list.html', context)

def detail(request, question_id):
    """
    pybo 내용 출력
    """
    question=get_object_or_404(Question, pk=question_id)
    context = {'question':question}
    return render(request, 'pybo/question_detail.html',context)

def answer_create(request, question_id):
    """
    pybo 답변 등록
    """
    question=get_object_or_404(Question, pk=question_id)
    question.answer_set.create(content=request.POST.get('content'),
                               create_date=timezone.now())
    return redirect('pybo:detail', question_id=question_id)

templates/pybo/question_detail.html
<h1>{{ question.subject }}</h1>
<div>
    {{ question.content }}
</div>
<h5>{{ question.answer_set.count }}개의 답변이 있습니다.</h5>
<div>
    <u1>
        {% for answer in question.answer_set.all %}
          <li>{{ answer.content }}</li>
        {% endfor %}
    </u1>
</div>

<form action="{%  url 'pybo:answer_create' question.id %}" method="post">
    {%  csrf_token %}
    <textarea name="content" id="content" rows="15"></textarea>
    <input type="submit" value="답변 등록">
</form>

templates/pybo/question_list.html
{% if question_list %}
    <ul>
        {%  for question in question_list %}
        <li><a href="{% url 'pybo:detail' question.id %}">{{question.subject}}</a></li>
        {%  endfor %}
    </ul>
{% else %}
    <p> 질문이 없습니다.</p>

{% endif %}